### ISSUE TITLE
Repeating File Cache Conflict since version 0.3

### ISSUE THREAD

**Issue by adriankirchner** [Haehnchen/idea-php-oxid-plugin#4]
Hello,

this morning I updated the OXID PhpStorm plugin from version 0.2.1 to 0.3. Since then I get a PhpStorm file cache conflict every few seconds to minutes:
![phpstorm_error](https://cloud.githubusercontent.com/assets/149483/8802054/120dc63a-2fbf-11e5-9918-f933a0f42b8a.png)

I'll send you a screenshot of the actual diff via email.
PhpStorm PS-141.1912 running on Windows 8.1 with samba share mounted.
Please ping me if you need any further information.

Cheers
Adrian

**Comment by MantasVaitkunas** [comment]
+1

**Comment by Haehnchen** [comment]
fixed 0.3.1. pls give some feedback

**Comment by adriankirchner** [comment]
v 0.3.1 fixed this issue. Thanks you for the quick bugfix.
